export const cityMapping: { [key: string]: string } = {
    '臺北': 'taipei',
    '臺北市': 'taipei',
    '台北': 'taipei',
    '台北市': 'taipei',
    '新北': 'new taipei',
    '新北市': 'new taipei',
    '桃園': 'taoyuan',
    '桃園市': 'taoyuan',
    '臺中': 'taichung',
    '臺中市': 'taichung',
    '台中': 'taichung',
    '台中市': 'taichung',
    '臺南': 'tainan',
    '臺南市': 'tainan',
    '台南': 'tainan',
    '台南市': 'tainan',
    '高雄': 'kaohsiung',
    '高雄市': 'kaohsiung',
    '基隆': 'keelung',
    '基隆市': 'keelung',
    '新竹': 'hsinchu',
    '新竹市': 'hsinchu',
    '新竹縣': 'hsinchu',
    '嘉義': 'chiayi',
    '嘉義市': 'chiayi',
    '嘉義縣': 'chiayi',
    '苗栗': 'miaoli',
    '苗栗縣': 'miaoli',
    '彰化': 'changhua',
    '彰化縣': 'changhua',
    '南投': 'nantou',
    '南投縣': 'nantou',
    '雲林': 'yunlin',
    '雲林縣': 'yunlin',
    '屏東': 'pingtung',
    '屏東縣': 'pingtung',
    '宜蘭': 'yilan',
    '宜蘭縣': 'yilan',
    '花蓮': 'hualien',
    '花蓮縣': 'hualien',
    '臺東': 'taitung',
    '臺東縣': 'taitung',
    '台東': 'taitung',
    '台東縣': 'taitung',
    '澎湖': 'penghu',
    '澎湖縣': 'penghu',
    '金門': 'kinmen',
    '金門縣': 'kinmen',
    '連江': 'lienchiang',
    '連江縣': 'lienchiang',
};

export const englishToChineseMapping: { [key: string]: string } = {
    'taipei': '臺北',
    'new taipei': '新北',
    'taoyuan': '桃園',
    'taichung': '臺中',
    'tainan': '臺南',
    'kaohsiung': '高雄',
    'keelung': '基隆',
    'hsinchu': '新竹',
    'chiayi': '嘉義',
    'miaoli': '苗栗',
    'changhua': '彰化',
    'nantou': '南投',
    'yunlin': '雲林',
    'pingtung': '屏東',
    'yilan': '宜蘭',
    'hualien': '花蓮',
    'taitung': '臺東',
    'penghu': '澎湖',
    'kinmen': '金門',
    'lienchiang': '連江',
};